services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=stockanalyzer'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
