version: "3.9"

services:
  market-data-ingestion:
    build: .
    container_name: market-data-ingestion
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
     SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
     SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
     SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
     GROWW_API_KEY: ${GROWW_API_KEY}
     GROWW_API_SECRET: ${GROWW_API_SECRET}